### ISSUE TITLE
RuntimeException: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by prodatax** [Mklueh/AndroidAchievementUnlocker#2]
Hi, 
I have been trying to run your Example project but i keep getting a RuntimeException error.
After my first failed attempt I updated my Android studio, SDK's, Build tools and Java.
Then I imported the project successfully but still get the RuntimeException error.

Below is my logcat report.

Thanks.

01-31 13:36:29.764 1650-1650/com.kluehspies.marian.example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.kluehspies.marian.example, PID: 1650
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kluehspies.marian.example/com.kluehspies.marian.example.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                              Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                                 at com.kluehspies.marian.unlockmanager.manager.RewardManager.notifyListeners(RewardManager.java:164)
                                                                                 at com.kluehspies.marian.unlockmanager.manager.RewardManager.unlockFailed(RewardManager.java:147)
                                                                                 at com.kluehspies.marian.unlockmanager.trigger.AndroidAchievementUnlocker.unlockFailed(AndroidAchievementUnlocker.java:99)
                                                                                 at com.kluehspies.marian.unlockmanager.trigger.SharedPreferencesHandler.triggerCurrentUnlockState(SharedPreferencesHandler.java:50)
                                                                                 at com.kluehspies.marian.unlockmanager.manager.RewardManager.triggerCurrentUnlockState(RewardManager.java:110)
                                                                                 at com.kluehspies.marian.unlockmanager.trigger.AndroidAchievementUnlocker.triggerUnlockIfAvailable(AndroidAchievementUnlocker.java:37)
                                                                                 at com.kluehspies.marian.example.MainActivity.onCreate(MainActivity.java:89)
                                                                                 at android.app.Activity.performCreate(Activity.java:6237)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
01-31 13:43:02.060 6060-6060/com.kluehspies.marian.example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.kluehspies.marian.example, PID: 6060
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kluehspies.marian.example/com.kluehspies.marian.example.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                              Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                                 at com.kluehspies.marian.unlockmanager.manager.RewardManager.notifyListeners(RewardManager.java:164)
                                                                                 at com.kluehspies.marian.unlockmanager.manager.RewardManager.unlockFailed(RewardManager.java:147)
                                                                                 at com.kluehspies.marian.unlockmanager.trigger.AndroidAchievementUnlocker.unlockFailed(AndroidAchievementUnlocker.java:99)
                                                                                 at com.kluehspies.marian.unlockmanager.trigger.SharedPreferencesHandler.triggerCurrentUnlockState(SharedPreferencesHandler.java:50)
                                                                                 at com.kluehspies.marian.unlockmanager.manager.RewardManager.triggerCurrentUnlockState(RewardManager.java:110)
                                                                                 at com.kluehspies.marian.unlockmanager.trigger.AndroidAchievementUnlocker.triggerUnlockIfAvailable(AndroidAchievementUnlocker.java:37)
                                                                                 at com.kluehspies.marian.example.MainActivity.onCreate(MainActivity.java:90)
                                                                                 at android.app.Activity.performCreate(Activity.java:6237)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by mklueh** [comment]
Hi prodatax,

the bug should be fixed now.

Best regards,

Marian

**Comment by prodatax** [comment]
Yes, thanks its working just fine now.
